shorter/urls.py
from django.urls import path
from shorter import views

app_name = 'shorter'

urlpatterns = [
    path('', views.index, name='home'),
    path('shorten/', views.get_shorten_url, name='get-shorten'),
    path('my-urls/', views.user_urls, name='user-urls'),
    path('stats/', views.statistics, name='stats'),
    path('<str:url_id>/', views.get_original_url, name='get-origin'),
]

url_short/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('shorter.urls', namespace='shorter')),
]

shorter/models.py
from django.db import models
from django.conf import settings


class Url(models.Model):
    url_id = models.SlugField(max_length=6, primary_key=True)
    url = models.URLField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    count = models.IntegerField(default=0)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.url

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):

    def __str__(self):
        return self.email

shorter/forms.py
from django.forms import ModelForm

from shorter.models import Url


class UrlShortenerForm(ModelForm):
    class Meta:
        model = Url
        fields = ['url']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = CustomUser
        fields = ('username', 'email',)

shorter/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.template.context_processors import csrf
import json

from shorter.models import Url
# from shorter.forms import UrlShortenerForm
from shorter.utils import get_short_code_for_url


def index(request):
    # form = UrlShortenerForm
    c = {}
    c.update(csrf(request))
    return render(request, 'shorter/index.html', c)


def get_original_url(request, url_id):
    url = get_object_or_404(Url, pk=url_id)
    url.count += 1
    url.save()

    if any(url.url.startswith(prt) for prt in ['https', 'http']):
        return HttpResponseRedirect(url.url)
    else:
        if url.url.startswith('www.'):
            return HttpResponseRedirect('http://' + url.url.strip('www.'))
        return HttpResponseRedirect('http://' + url.url)


def get_shorten_url(request):
    url = request.POST.get('url', '')

    if url != '':
        url_id = get_short_code_for_url()
        b = Url(url_id=url_id, url=url, created_by=request.user)
        b.save()

        response_data = dict()
        response_data['url'] = settings.SITE_URL + url_id
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    return HttpResponse(json.dumps({"error": "error occurs"}), content_type="application/json")


def user_urls(request):
    if request.user.is_authenticated:
        urls = Url.objects.filter(created_by=request.user)
        site_url = settings.SITE_URL
        return render(request, 'shorter/user_urls.html', {'urls': urls, 'site_url': site_url})
    return redirect('/')


def statistics(request):
    if request.user.is_authenticated:
        urls = Url.objects.filter(created_by=request.user)
        site_url = settings.SITE_URL
        return render(request, 'shorter/user_urls_stats.html', {'urls': urls, 'site_url': site_url})
    return redirect('/')

users/views.py
from django.shortcuts import render

# Create your views here.

templates/shorter/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}Url shortening service {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<script type="text/javascript">
    $(function() {
        $('#submitButton').click(function() {
            $.ajax({
                type: "POST",
                url: "/shorten/",
                data: {
                    'url' : $('#url').val(),
                    'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
                },
            success: returnSuccess,
            dataType: 'json'
            });
        });
    });

    function returnSuccess(data, textStatus, jqXHR) {
        if(data.url) {
            $('#url-result').text(data.url);
            $('#url').val("");
        } else {
            $('#url-result').text("Do not submit blank.");
        }

    }
</script>
<body>
    <ul class="nav justify-content-center">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'shorter:home' %}">URL shortener</a>
        </li>
        {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shorter:user-urls' %}">My urls</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shorter:stats' %}">Statistics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link disabled" href="{% url 'account_login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="{% url 'account_signup' %}">Sign Up</a>
            </li>
        {% endif %}
    </ul>
    <div id="wrap">
        <header>
            <h1><a href="{% url 'shorter:home' %}">URL shortener</a></h1>
        </header>
        <div id="content">
            {% block content %}

            {% endblock %}
        </div>
     </div>
</body>
</html>

templates/shorter/index.html
{% extends 'shorter/base.html' %}

{% block title %}
    Make your url shorter!
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-sm-9">
                <input type="text" name="url" id="url" class="form-control input-sm" placeholder="Enter your url ...">
            </div>
            <div class="col-sm-3">
                {% csrf_token %}
                <p></p>
                <button id="submitButton" class="btn btn-primary">Submit</button>
            </div>
        </div>
        <div class="panel-footer"><span id="url-result">Enter the URL above and click submit!</span></div>
    </div>
{% endblock %}

templates/shorter/user_urls.html
{% extends 'shorter/base.html' %}
{% block title %}
    My urls
{% endblock %}
{% block content %}
    {% for url in urls %}
        <a href="/{{ url.url_id }}" target="_blank">{{ site_url }}{{ url.url_id }} </a><small>{{ url.url }}</small>
        <p></p>
    {% endfor %}
{% endblock %}

templates/shorter/user_urls_stats.html
{% extends 'shorter/base.html' %}
{% block title %}
    Statistics for my urls
{% endblock %}
{% block content %}
    {% for url in urls %}
        <a href="/{{ url.url_id }}" target="_blank">{{ site_url }}{{ url.url_id }} --- </a><small>{{ url.url }} --- </small><small>Count: {{ url.count }}</small>
        <p></p>
    {% endfor %}
{% endblock %}